package com.dicoding.genshinapplication;

import java.util.ArrayList;

public class CharacterData {
    public static String[] characterName = {
            "Albedo",
            "Aloy",
            "Amber",
            "Barbara",
            "Beidou",
            "Bennett",
            "Chongyun",
            "Diluc",
            "Diona",
            "Eula",
            "Fischl",
            "Ganyu",
            "Hu Tao",
            "Jean",
            "Kaedehara Kazuha",
            "Kaeya",
            "Kamisato Ayaka",
            "Keqing",
            "Klee",
            "Kujou Sara",
            "Lisa",
            "Mona",
            "Ningguang",
            "Noelle",
            "Qiqi",
            "Raiden Shogun",
            "Razor",
            "Rosaria",
            "Sangonomiya Kokomi",
            "Sayu",
            "Shenhe",
            "Sucrose",
            "Tartaglia",
            "Thoma",
            "Traveler",
            "Venti",
            "Xiangling",
            "Xiao",
            "Xingqiu",
            "Xinyan",
            "Yae Miko",
            "Yanfei",
            "Yoimiya",
            "Yun Jin",
            "Zhongli"
    };

    public static String[] characterAbility = {
            "Geo, Sword",
            "Cryo, Bow",
            "Pyro, Bow",
            "Hydro, Catalyst",
            "Electro, Claymore",
            "Pyro, Sword",
            "Cryo, Claymore",
            "Pyro, Claymore",
            "Cryo, Bow",
            "Cryo, Claymore",
            "Electro, Bow",
            "Cryo, Bow",
            "Pyro, Polearm",
            "Anemo, Sword",
            "Anemo, Sword",
            "Cryo, Sword",
            "Cryo, Sword",
            "Electro, Sword",
            "Pyro, Catalyst",
            "Electro, Bow",
            "Electro, Catalyst",
            "Hydro, Catalyst",
            "Geo, Catalyst",
            "Geo, Claymore",
            "Cryo, Sword",
            "Electro, Polearm",
            "Electro, Claymore",
            "Cryo, Polearm",
            "Hydro, Catalyst",
            "Anemo, Claymore",
            "Cryo, Polearm",
            "Anemo, Catalyst",
            "Hydro, Bow",
            "Pyro, Polearm",
            "Adaptive, Sword",
            "Anemo, Bow",
            "Pyro, Polearm",
            "Anemo, Polearm",
            "Hydro, Sword",
            "Pyro, Claymore",
            "Electro, Catalyst",
            "Pyro, Catalyst",
            "Pyro, Bow",
            "Geo, Polearm",
            "Geo, Polearm"
    };

    public static int[] characterPhoto = {
            R.drawable.albedo,
            R.drawable.aloy,
            R.drawable.amber,
            R.drawable.barbara,
            R.drawable.beidou,
            R.drawable.bennett,
            R.drawable.chongyun,
            R.drawable.diluc,
            R.drawable.diona,
            R.drawable.eula,
            R.drawable.fischl,
            R.drawable.ganyu,
            R.drawable.hu_tao,
            R.drawable.jean,
            R.drawable.kaedehara_kazuha,
            R.drawable.kaeya,
            R.drawable.kamisato_ayaka,
            R.drawable.keqing,
            R.drawable.klee,
            R.drawable.kujou_sara,
            R.drawable.lisa,
            R.drawable.mona,
            R.drawable.ningguang,
            R.drawable.noelle,
            R.drawable.qiqi,
            R.drawable.raiden_shogun,
            R.drawable.razor,
            R.drawable.rosaria,
            R.drawable.sangonomiya_kokomi,
            R.drawable.sayu,
            R.drawable.shenhe,
            R.drawable.sucrose,
            R.drawable.tartaglia,
            R.drawable.thoma,
            R.drawable.traveler,
            R.drawable.venti,
            R.drawable.xiangling,
            R.drawable.xiao,
            R.drawable.xingqiu,
            R.drawable.xinyan,
            R.drawable.yae_miko,
            R.drawable.yanfei,
            R.drawable.yoimiya,
            R.drawable.yun_jin,
            R.drawable.zhongli
    };

    public static String[] characterInfo = {
            "A synthetic human made by the alchemist Rhinedottir, the mysterious Albedo is the Chief Alchemist and Captain of the Investigation Team of the Knights of Favonius. Through a recommendation from the adventurer Alice, with Sucrose as his assistant, he holds an infinite desire to learn about the world of Teyvat, carefully studying every object around him.",
            "She is the heroine from Horizon Zero Dawn and is introduced as a collaboration and crossover character between Guerrilla Games and miHoYo.",
            "As the only remaining Outrider of the Knights of Favonius, she is always ready to help the citizens of Mondstadt — whether it be something simple or perhaps a more challenging task.",
            "She is the deaconess of the Church of Favonius and a self-proclaimed \"idol\" after learning about them from the intrepid adventurer Alice. She is also the daughter of Frederica Gunnhildr and Seamus Pegg, and the younger sister of Jean. Through Frederica she is a descendant of the prestigious Gunnhildr Clan.",
            "She is the captain of The Crux, a renowned crew in Liyue. Besides her capabilities as a fleet captain and her immense strength, many in Liyue know her for her lack of fear towards the Tianquan of the Liyue Qixing, Ningguang — a trait that the other woman appreciates, yet grows irritated by.",
            "An orphan discovered by an elderly adventurer as a baby, Bennett was raised in Mondstadt's Adventurers' Guild. He is the one and only member of \"Benny's Adventure Team,\" as everyone else left the team after experiencing the constant misfortune that follows him.",
            "An exorcist from Liyue, Chongyun was born with excessive yang (positive) energy, which has proven to be both a help and a hindrance. It makes him a very effective exorcist, but it also means he has never seen a spirit for himself — they flee before he can even lay eyes on them. It has also made him particularly susceptible to any kind of heat or strong emotion, which leads to some rather... unexpected results.",
            "Born into the affluent Ragnvindr Clan, Diluc is the current owner of the Dawn Winery and a nobleman of high esteem in Mondstadt society. While a past incident caused him to split ways with the Knights of Favonius, he continues to protect Mondstadt in his own way.",
            "Despite being a bartender at Cat's Tail, she actually despises alcohol and wants nothing more than to ruin Mondstadt's wine industry—a feat easier said than done when her patrons absolutely love her drinks. She is the daughter of Draff, a hunter in Springvale.",
            "A descendant of the infamous and tyrannical Lawrence Clan and niece of Schubert, Eula is the captain of the Reconnaissance Company with the Knights of Favonius.",
            "Fischl is an investigator for Mondstadt's Adventurers' Guild, accompanied by the night raven Oz. Fischl claims to hail from a world beyond Teyvat. She is a daring adventurer with seemly outlandish theories that happen to turn out to be true.",
            "She serves as an emissary and secretary for the Liyue Qixing.",
            "She is the 77th Director of the Wangsheng Funeral Parlor.",
            "The daughter of Frederica Gunnhildr and Seamus Pegg, the older sister of Barbara, and a descendant of the prestigious Gunnhildr Clan, Jean is the Acting Grand Master of the Knights of Favonius. She is always busy handling unrest across Mondstadt and of course, tirelessly working to maintain the City of Freedom.",
            "A wandering samurai of the once-famed Kaedehara Clan, Kazuha is a temporary crewmember of The Crux.",
            "Kaeya is the Cavalry Captain of the Knights of Favonius. He is held in high regard by the people of Mondstadt — even with all his eccentricities and secrets.",
            "She is the oldest daughter of the Kamisato Clan and sister of Kamisato Ayato. Being beautiful, elegant, and graceful, the common folk have nothing to bad-mouth Ayaka about. Because of her social status as the eldest daughter of the Kamisato Clan of the Yashiro Commission and as the Shirasagi Himegimi, Ayaka is seen as a model of perfection.",
            "As the Yuheng of the Liyue Qixing, she is someone who seeks her own answers instead of idly letting chaos run amok in Liyue. She chooses her own path with her own power and ability, instead of letting the gods determine her fate.",
            "The daughter of the intrepid and often quite destructive adventurer Alice, Klee takes after her mother in many ways, much to the dismay of the Knights of Favonius whom she has been entrusted to.",
            "A tengu, Sara is the adopted daughter of the Kujou Clan of the Tenryou Commission. Loyal to both her clan and the Shogun, Kujou Sara carries out her orders to the Shogun's will.",
            "A powerful mage recognized as Sumeru Academia's most distinguished graduate in 200 years, Lisa has since returned to Mondstadt to become the humble Librarian of the Knights of Favonius.",
            "An astrologist of great skill and equally-great pride, Mona has taken up residence in Mondstadt to avoid incurring the wrath of her master after unwittingly reading the latter's diary.",
            "She is the Tianquan of the Liyue Qixing and owns the floating Jade Chamber in the skies of Liyue.",
            "While not yet a knight, she seeks to one day join the Knights of Favonius by first serving as a dutiful maid.",
            "Resurrected as a zombie by the adepti, she has ended up in Baizhu's care and now works at Bubu Pharmacy in Liyue Harbor.",
            "She is the vessel of Beelzebul, the current Electro Archon of Inazuma.",
            "Abandoned as an infant, Razor was taken in by the Wolf of the North, Andrius, and raised by his wolf pack in Wolvendom. After a chance encounter with Varka, the current Grand Master of the Knights of Favonius and the Knight of Boreas, he has slowly started integrating with humans again.",
            "She is a member of the Church of Favonius in Mondstadt.",
            "The young Divine Priestess of Watatsumi Island and a descendant of the Sangonomiya Clan. Kokomi is in charge of most of Watatsumi's affairs, shouldering heavy responsibilities alone in hopes for giving Watatsumi Island's people the hopes and happiness that they desire.",
            "A ninja from the Shuumatsuban that is struggling with growing tall. Sayu believes that sleeping can help her growth, which is why she prefers to use her ninja techniques to hide and \"laze around.\"",
            "The daughter of an unnamed exorcist couple, Shenhe was taken in by Cloud Retainer as a disciple following a traumatic incident during her childhood.",
            "An alchemist specializing in bio-alchemy, she also serves as an assistant for Albedo, the head alchemist of the Knights of Favonius.",
            "He is the Eleventh of the Fatui Harbingers. Following danger wherever he goes, Childe is always eager for a challenge, making him extremely dangerous despite being the youngest member.",
            "Hailing from Mondstadt, he is the housekeeper for the Kamisato Clan, and also a well-known \"fixer\" in Inazuma.",
            "At the beginning of the game, both genders are twin siblings from another world, traveling throughout the universe, until an unknown god blocked and captured one of them, and sealed their power to travel, leaving them stranded on Teyvat. They are accompanied by a travel companion named Paimon throughout their journey.",
            "He is a free-spirited, wine-loving bard in Mondstadt and the current mortal vessel of Barbatos, the Anemo Archon.",
            "She is the Head Chef at the Wanmin Restaurant and runs it alongside her father Chef Mao. As a chef, Xiangling isn't afraid to try out different recipes or \"exotic\" ingredients... making her dishes sometimes quite unique.",
            "He is an adeptus, under the name Alatus, and the only known remaining member of the five foremost Yakshas dispatched by Morax to subdue the demonic spirits that plagued Liyue. He currently resides in Wangshu Inn and mostly secludes himself from crowds and human interactions.",
            "He is the second son of the Guild Manager of the Feiyun Commerce Guild, an influential group in Liyue, and is also a self-proclaimed practitioner of the Guhua Clan's arts.",
            "Rock 'n' roll is a relatively unpopular style of music in Liyue, having recently been brought over from Fontaine. Xinyan, however, loves the sound — and she's slowly but surely amassing a fanbase of her own as she performs throughout Liyue Harbor.",
            "Miko oversees the Grand Narukami Shrine and is the owner of the Yae Publishing House.",
            "She is the child of an adeptus father and human mother. After she grew up, her parents left to go on an adventure, placing her in the care of Madame Ping. She resides in Liyue, serving as a legal advisor for its people.",
            "She is the daughter of Naganohara Ryuunosuke and the current owner of Naganohara Fireworks. With her colorful fireworks and outgoing personality, Yoimiya is beloved by everyone on Narukami Island, who believes summer is not the same without her.",
            "She is a prestigious dancer, singer, and brewer who works at the Heyu Tea House.",
            "He is a consultant of the Wangsheng Funeral Parlor. He is later revealed to be the current vessel of the Geo Archon, Morax, who has decided to experience the world from the perspective of a mortal."
    };

    public static String[] characterArtifactOne = {
            "2-Piece Bonus : DEF 30%",
            "2-Piece Bonus : Cryo DMG Bonus +15%",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "2-Piece Bonus : Character Healing Effectiveness +15%",
            "2-Piece Bonus : Electro DMG Bonus +15%",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "2-Piece Bonus : Cryo DMG Bonus +15%",
            "2-Piece Bonus : Pyro DMG Bonus +15%",
            "2-Piece Bonus : Character Healing Effectiveness +15%",
            "2-Piece Bonus : Physical DMG +25%",
            "2-Piece Bonus : Electro DMG Bonus +15%",
            "2-Piece Bonus : Increases Elemental Mastery by 80.",
            "2-Piece Bonus : Pyro DMG Bonus +15%",
            "2-Piece Bonus : Anemo DMG Bonus +15%",
            "2-Piece Bonus : Anemo DMG Bonus +15%",
            "2-Piece Bonus : Cryo DMG Bonus +15%",
            "2-Piece Bonus : Cryo DMG Bonus +15%",
            "2-Piece Bonus : Electro DMG Bonus +15%",
            "2-Piece Bonus : Pyro DMG Bonus +15%",
            "2-Piece Bonus : Electro DMG Bonus +15%",
            "2-Piece Bonus : Electro DMG Bonus +15%",
            "2-Piece Bonus : Increases Elemental Mastery by 80.",
            "2-Piece Bonus : Geo DMG Bonus +15%",
            "2-Piece Bonus : Increases Shield Strength by 35%",
            "2-Piece Bonus : Healing Bonus +15%",
            "2-Piece Bonus : Energy Recharge +20%",
            "2-Piece Bonus : Physical DMG +25%",
            "2-Piece Bonus : Cryo DMG Bonus +15%",
            "2-Piece Bonus : Healing Bonus +15%",
            "2-Piece Bonus : Anemo DMG Bonus +15%",
            "2-Piece Bonus : ATK +18%",
            "2-Piece Bonus : Anemo DMG Bonus +15%",
            "2-Piece Bonus : Hydro DMG Bonus +15%",
            "2-Piece Bonus : HP +20%",
            "2-Piece Bonus : ATK +18%",
            "2-Piece Bonus : Anemo DMG Bonus +15%",
            "2-Piece Bonus : Energy Recharge +20%",
            "2-Piece Bonus : Anemo DMG Bonus +15%",
            "2-Piece Bonus : Hydro DMG Bonus +15%",
            "2-Piece Bonus : Physical DMG +25%",
            "2-Piece Bonus : Electro DMG Bonus +15%",
            "2-Piece Bonus : Increases Elemental Mastery by 80.",
            "2-Piece Bonus : ATK +18%",
            "2-Piece Bonus : DEF 30%",
            "2-Piece Bonus : HP +20%"
    };

    public static String[] characterArtifactTwo = {
            "4-Piece Bonus : A character equipped with this Artifact set will obtain the Curiosity effect in the following conditions: When on the field, the character gains 1 stack after hitting an opponent with a Geo attack, triggering a maximum of once every 0.3s.\n" +
                    "When off the field, the character gains 1 stack every 3s. Curiosity can stack up to 4 times, each providing 6% DEF and a 6% Geo DMG Bonus. When 6 seconds pass without gaining a Curiosity stack, 1 stack is lost.",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "4-Piece Bonus : Using an Elemental Burst increases all party members' ATK by 20% for 12s. This effect cannot stack.",
            "4-Piece Bonus : Using an Elemental Skill or Burst increases healing received by all party members by 20% for 10s.",
            "2-Piece Bonus : ATK +18%",
            "4-Piece Bonus : Using an Elemental Burst increases all party members' ATK by 20% for 12s. This effect cannot stack.",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "4-Piece Bonus : Increases Overloaded and Burning DMG by 40%. Increases Vaporize and Melt DMG by 15%. Using an Elemental Skill increases the 2-Piece Set Bonus by 50% of its starting value for 10s. Max 3 stacks.",
            "2-Piece Bonus : HP +20%",
            "4-Piece Bonus : When an Elemental Skill hits an opponent, ATK is increased by 9% for 7s. This effect stacks up to 3 times and can be triggered once every 0.3s. Once 3 stacks are reached, the 2-set effect is increased by 100%",
            "4-Piece Bonus : Increases damage caused by Overloaded, Electro-Charged and Superconduct by 40%. Triggering such effects decreases Elemental Skill CD by 1s. Can only occur once every 0.8s.",
            "4-Piece Bonus : Increases Charged Attack DMG by 35% if the character uses a Catalyst or Bow.",
            "4-Piece Bonus : Increases Overloaded and Burning DMG by 40%. Increases Vaporize and Melt DMG by 15%. Using an Elemental Skill increases the 2-Piece Set Bonus by 50% of its starting value for 10s. Max 3 stacks.",
            "2-Piece Bonus : ATK +18%",
            "4-Piece Bonus : Increases Swirl DMG by 60%. Decreases opponent's Elemental RES to the element infused in the Swirl by 40% for 10s.",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "4-Piece Bonus : When a character attacks an opponent affected by Cryo, their CRIT Rate is increased by 20%. If the opponent is Frozen, CRIT Rate is increased by an additional 20%",
            "2-Piece Bonus : ATK +18%",
            "4-Piece Bonus : Increases Overloaded and Burning DMG by 40%. Increases Vaporize and Melt DMG by 15%. Using an Elemental Skill increases the 2-Piece Set Bonus by 50% of its starting value for 10s. Max 3 stacks.",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "4-Piece Bonus : Upon triggering an Elemental Reaction, increases all party members' Elemental Mastery by 120 for 8s.",
            "2-Piece Bonus : ATK +18%",
            "4-Piece Bonus : While protected by a shield, gain an additional 40% Normal and Charged Attack DMG.",
            "4-Piece Bonus : When the character equipping this artifact set heals a character in the party, a Sea-Dyed Foam will appear for 3 seconds, accumulating the amount of HP recovered from healing (including overflow healing).\n" +
                    "At the end of the duration, the Sea-Dyed Foam will explode, dealing DMG to nearby opponents based on 90% of the accumulated healing.\n" +
                    "(This DMG is calculated similarly to Reactions such as Electro-Charged, and Superconduct, but it is not affected by Elemental Mastery, Character Levels, or Reaction DMG Bonuses).\n" +
                    "Only one Sea-Dyed Foam can be produced every 3.5 seconds.\n" +
                    "Each Sea-Dyed Foam can accumulate up to 30,000 HP (including overflow healing).\n" +
                    "There can be no more than one Sea-Dyed Foam active at any given time.\n" +
                    "This effect can still be triggered even when the character who is using this artifact set is not on the field.",
            "4-Piece Bonus : Increases Elemental Burst DMG by 25% of Energy Recharge. A maximum of 75% bonus DMG can be obtained in this way.",
            "2-Piece Bonus : Physical DMG +25%",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "4-Piece Bonus : When the character equipping this artifact set heals a character in the party, a Sea-Dyed Foam will appear for 3 seconds, accumulating the amount of HP recovered from healing (including overflow healing).\n" +
                    "At the end of the duration, the Sea-Dyed Foam will explode, dealing DMG to nearby opponents based on 90% of the accumulated healing.\n" +
                    "(This DMG is calculated similarly to Reactions such as Electro-Charged, and Superconduct, but it is not affected by Elemental Mastery, Character Levels, or Reaction DMG Bonuses).\n" +
                    "Only one Sea-Dyed Foam can be produced every 3.5 seconds.\n" +
                    "Each Sea-Dyed Foam can accumulate up to 30,000 HP (including overflow healing).\n" +
                    "There can be no more than one Sea-Dyed Foam active at any given time.\n" +
                    "This effect can still be triggered even when the character who is using this artifact set is not on the field.",
            "4-Piece Bonus : Increases Swirl DMG by 60%. Decreases opponent's Elemental RES to the element infused in the Swirl by 40% for 10s.",
            "2-Piece Bonus : ATK +18%",
            "4-Piece Bonus : Increases Swirl DMG by 60%. Decreases opponent's Elemental RES to the element infused in the Swirl by 40% for 10s.",
            "4-Piece Bonus : After using an Elemental Skill, increases Normal Attack and Charged Attack DMG by 30% for 15s.",
            "2-Piece Bonus : Energy Recharge +20%",
            "4-Piece Bonus : If the wielder of this artifact set uses a Sword, Claymore or Polearm, increases their Normal Attack DMG by 35%",
            "4-Piece Bonus : Increases Swirl DMG by 60%. Decreases opponent's Elemental RES to the element infused in the Swirl by 40% for 10s.",
            "4-Piece Bonus : Increases Elemental Burst DMG by 25% of Energy Recharge. A maximum of 75% bonus DMG can be obtained in this way.",
            "2-Piece Bonus : ATK +18%",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "2-Piece Bonus : Physical DMG +25%",
            "2-Piece Bonus : Elemental Burst DMG +20%",
            "4-Piece Bonus : Increases Charged Attack DMG by 35% if the character uses a Catalyst or Bow.",
            "4-Piece Bonus : When casting an Elemental Skill, if the character has 15 or more Energy, they lose 15 Energy and Normal/Charged/Plunging Attack DMG is increased by 50% for 10s. This effect will not trigger again during that duration.",
            "4-Piece Bonus : A character equipped with this Artifact set will obtain the Curiosity effect in the following conditions: When on the field, the character gains 1 stack after hitting an opponent with a Geo attack, triggering a maximum of once every 0.3s.\n" +
                    "When off the field, the character gains 1 stack every 3s. Curiosity can stack up to 4 times, each providing 6% DEF and a 6% Geo DMG Bonus. When 6 seconds pass without gaining a Curiosity stack, 1 stack is lost.",
            "4-Piece Bonus : When an Elemental Skill hits an opponent, the ATK of all nearby party members is increased by 20% and their Shield Strength is increased by 30% for 3s. This effect can be triggered once every 0.5s. This effect can still be triggered even when the character who is using this artifact set is not on the field."
    };

    public static int[] characterCard = {
            R.drawable.albedo_card,
            R.drawable.aloy_card,
            R.drawable.amber_card,
            R.drawable.barbara_card,
            R.drawable.beidou_card,
            R.drawable.bennett_card,
            R.drawable.chongyun_card,
            R.drawable.diluc_card,
            R.drawable.diona_card,
            R.drawable.eula_card,
            R.drawable.fischl_card,
            R.drawable.ganyu_card,
            R.drawable.hu_tao_card,
            R.drawable.jean_card,
            R.drawable.kaedehara_kazuha_card,
            R.drawable.kaeya_card,
            R.drawable.kamisato_ayaka_card,
            R.drawable.keqing_card,
            R.drawable.klee_card,
            R.drawable.kujou_sara_card,
            R.drawable.lisa_card,
            R.drawable.mona_card,
            R.drawable.ningguang_card,
            R.drawable.noelle_card,
            R.drawable.qiqi_card,
            R.drawable.raiden_shogun_card,
            R.drawable.razor_card,
            R.drawable.rosaria_card,
            R.drawable.sangonomiya_kokomi_card,
            R.drawable.sayu_card,
            R.drawable.shenhe_card,
            R.drawable.sucrose_card,
            R.drawable.tartaglia_card,
            R.drawable.thoma_card,
            R.drawable.traveler_card,
            R.drawable.venti_card,
            R.drawable.xiangling_card,
            R.drawable.xiao_card,
            R.drawable.xingqiu_card,
            R.drawable.xinyan_card,
            R.drawable.yae_miko_card,
            R.drawable.yanfei_card,
            R.drawable.yoimiya_card,
            R.drawable.yun_jin_card,
            R.drawable.zhongli_card
    };

    public static int[] characterVision = {
            R.drawable.geo,
            R.drawable.cryo,
            R.drawable.pyro,
            R.drawable.hydro,
            R.drawable.electro,
            R.drawable.pyro,
            R.drawable.cryo,
            R.drawable.pyro,
            R.drawable.cryo,
            R.drawable.cryo,
            R.drawable.electro,
            R.drawable.cryo,
            R.drawable.pyro,
            R.drawable.anemo,
            R.drawable.anemo,
            R.drawable.cryo,
            R.drawable.cryo,
            R.drawable.electro,
            R.drawable.pyro,
            R.drawable.electro,
            R.drawable.electro,
            R.drawable.hydro,
            R.drawable.geo,
            R.drawable.geo,
            R.drawable.cryo,
            R.drawable.electro,
            R.drawable.electro,
            R.drawable.cryo,
            R.drawable.hydro,
            R.drawable.anemo,
            R.drawable.cryo,
            R.drawable.anemo,
            R.drawable.hydro,
            R.drawable.pyro,
            R.drawable.nonvision,
            R.drawable.anemo,
            R.drawable.pyro,
            R.drawable.anemo,
            R.drawable.hydro,
            R.drawable.pyro,
            R.drawable.electro,
            R.drawable.pyro,
            R.drawable.pyro,
            R.drawable.geo,
            R.drawable.geo
    };

    public static int[] characterArtifacta = {
            R.drawable.huskofopulentdreams_1,
            R.drawable.blizzardstrayer_1,
            R.drawable.noblesseoblige_1,
            R.drawable.maidenbeloved_1,
            R.drawable.thunderingfury_1,
            R.drawable.noblesseoblige_1,
            R.drawable.blizzardstrayer_1,
            R.drawable.crimsonwitchofflames_1,
            R.drawable.maidenbeloved_1,
            R.drawable.paleflame_1,
            R.drawable.thunderingfury_1,
            R.drawable.wandererstroupe_1,
            R.drawable.crimsonwitchofflames_1,
            R.drawable.viridescentvenerer_1,
            R.drawable.viridescentvenerer_1,
            R.drawable.blizzardstrayer_1,
            R.drawable.blizzardstrayer_1,
            R.drawable.thunderingfury_1,
            R.drawable.crimsonwitchofflames_1,
            R.drawable.thunderingfury_1,
            R.drawable.thunderingfury_1,
            R.drawable.instructor_1,
            R.drawable.archaicpetra_1,
            R.drawable.retracingbolide_1,
            R.drawable.oceanhuedclam_1,
            R.drawable.emblemofseveredfate_1,
            R.drawable.paleflame_1,
            R.drawable.blizzardstrayer_1,
            R.drawable.oceanhuedclam_1,
            R.drawable.viridescentvenerer_1,
            R.drawable.gladiatorsfinale_1,
            R.drawable.viridescentvenerer_1,
            R.drawable.heartofdepth_1,
            R.drawable.tenacityofthemillelith_1,
            R.drawable.gladiatorsfinale_1,
            R.drawable.viridescentvenerer_1,
            R.drawable.emblemofseveredfate_1,
            R.drawable.viridescentvenerer_1,
            R.drawable.heartofdepth_1,
            R.drawable.bloodstainedchivalry_1,
            R.drawable.thunderingfury_1,
            R.drawable.wandererstroupe_1,
            R.drawable.shimenawasreminiscence_1,
            R.drawable.huskofopulentdreams_1,
            R.drawable.tenacityofthemillelith_1
    };

    public static int[] characterArtifactb = {
            R.drawable.huskofopulentdreams_2,
            R.drawable.blizzardstrayer_2,
            R.drawable.noblesseoblige_2,
            R.drawable.maidenbeloved_2,
            R.drawable.thunderingfury_2,
            R.drawable.noblesseoblige_2,
            R.drawable.blizzardstrayer_2,
            R.drawable.crimsonwitchofflames_2,
            R.drawable.maidenbeloved_2,
            R.drawable.paleflame_2,
            R.drawable.thunderingfury_2,
            R.drawable.wandererstroupe_2,
            R.drawable.crimsonwitchofflames_2,
            R.drawable.viridescentvenerer_2,
            R.drawable.viridescentvenerer_2,
            R.drawable.blizzardstrayer_2,
            R.drawable.blizzardstrayer_2,
            R.drawable.thunderingfury_2,
            R.drawable.crimsonwitchofflames_2,
            R.drawable.thunderingfury_2,
            R.drawable.thunderingfury_2,
            R.drawable.instructor_2,
            R.drawable.archaicpetra_2,
            R.drawable.retracingbolide_2,
            R.drawable.oceanhuedclam_2,
            R.drawable.emblemofseveredfate_2,
            R.drawable.paleflame_2,
            R.drawable.blizzardstrayer_2,
            R.drawable.oceanhuedclam_2,
            R.drawable.viridescentvenerer_2,
            R.drawable.gladiatorsfinale_2,
            R.drawable.viridescentvenerer_2,
            R.drawable.heartofdepth_2,
            R.drawable.tenacityofthemillelith_2,
            R.drawable.gladiatorsfinale_2,
            R.drawable.viridescentvenerer_2,
            R.drawable.emblemofseveredfate_2,
            R.drawable.viridescentvenerer_2,
            R.drawable.heartofdepth_2,
            R.drawable.bloodstainedchivalry_2,
            R.drawable.thunderingfury_2,
            R.drawable.wandererstroupe_2,
            R.drawable.shimenawasreminiscence_2,
            R.drawable.huskofopulentdreams_2,
            R.drawable.tenacityofthemillelith_2
    };

    public static int[] characterArtifactc = {
            R.drawable.huskofopulentdreams_3,
            R.drawable.noblesseoblige_3,
            R.drawable.noblesseoblige_3,
            R.drawable.maidenbeloved_3,
            R.drawable.gladiatorsfinale_3,
            R.drawable.noblesseoblige_3,
            R.drawable.noblesseoblige_3,
            R.drawable.crimsonwitchofflames_3,
            R.drawable.tenacityofthemillelith_3,
            R.drawable.paleflame_3,
            R.drawable.thunderingfury_3,
            R.drawable.wandererstroupe_3,
            R.drawable.crimsonwitchofflames_3,
            R.drawable.gladiatorsfinale_3,
            R.drawable.viridescentvenerer_3,
            R.drawable.noblesseoblige_3,
            R.drawable.blizzardstrayer_3,
            R.drawable.gladiatorsfinale_3,
            R.drawable.crimsonwitchofflames_3,
            R.drawable.noblesseoblige_3,
            R.drawable.noblesseoblige_3,
            R.drawable.instructor_3,
            R.drawable.gladiatorsfinale_3,
            R.drawable.retracingbolide_3,
            R.drawable.oceanhuedclam_3,
            R.drawable.emblemofseveredfate_3,
            R.drawable.bloodstainedchivalry_3,
            R.drawable.noblesseoblige_3,
            R.drawable.oceanhuedclam_3,
            R.drawable.viridescentvenerer_3,
            R.drawable.shimenawasreminiscence_3,
            R.drawable.viridescentvenerer_3,
            R.drawable.heartofdepth_3,
            R.drawable.emblemofseveredfate_3,
            R.drawable.gladiatorsfinale_3,
            R.drawable.viridescentvenerer_3,
            R.drawable.emblemofseveredfate_3,
            R.drawable.gladiatorsfinale_3,
            R.drawable.noblesseoblige_3,
            R.drawable.paleflame_3,
            R.drawable.noblesseoblige_3,
            R.drawable.wandererstroupe_3,
            R.drawable.shimenawasreminiscence_3,
            R.drawable.huskofopulentdreams_3,
            R.drawable.tenacityofthemillelith_3
    };

    public static int[] characterArtifactd = {
            R.drawable.huskofopulentdreams_4,
            R.drawable.noblesseoblige_4,
            R.drawable.noblesseoblige_4,
            R.drawable.maidenbeloved_4,
            R.drawable.gladiatorsfinale_4,
            R.drawable.noblesseoblige_4,
            R.drawable.noblesseoblige_4,
            R.drawable.crimsonwitchofflames_4,
            R.drawable.tenacityofthemillelith_4,
            R.drawable.paleflame_4,
            R.drawable.thunderingfury_4,
            R.drawable.wandererstroupe_4,
            R.drawable.crimsonwitchofflames_4,
            R.drawable.gladiatorsfinale_4,
            R.drawable.viridescentvenerer_4,
            R.drawable.noblesseoblige_4,
            R.drawable.blizzardstrayer_4,
            R.drawable.gladiatorsfinale_4,
            R.drawable.crimsonwitchofflames_4,
            R.drawable.noblesseoblige_4,
            R.drawable.noblesseoblige_4,
            R.drawable.instructor_4,
            R.drawable.gladiatorsfinale_4,
            R.drawable.retracingbolide_4,
            R.drawable.oceanhuedclam_4,
            R.drawable.emblemofseveredfate_4,
            R.drawable.bloodstainedchivalry_4,
            R.drawable.noblesseoblige_4,
            R.drawable.oceanhuedclam_4,
            R.drawable.viridescentvenerer_4,
            R.drawable.shimenawasreminiscence_4,
            R.drawable.viridescentvenerer_4,
            R.drawable.heartofdepth_4,
            R.drawable.emblemofseveredfate_4,
            R.drawable.gladiatorsfinale_4,
            R.drawable.viridescentvenerer_4,
            R.drawable.emblemofseveredfate_4,
            R.drawable.gladiatorsfinale_4,
            R.drawable.noblesseoblige_4,
            R.drawable.paleflame_4,
            R.drawable.noblesseoblige_4,
            R.drawable.wandererstroupe_4,
            R.drawable.shimenawasreminiscence_4,
            R.drawable.huskofopulentdreams_4,
            R.drawable.tenacityofthemillelith_4
    };

    static ArrayList<Character> getListData() {
        ArrayList<Character> list = new ArrayList<>();
        for(int position = 0; position < characterName.length; position++) {
            Character character = new Character();
            character.setName(characterName[position]);
            character.setAbility(characterAbility[position]);
            character.setPhoto(characterPhoto[position]);
            character.setInfo(characterInfo[position]);
            character.setArtifactOne(characterArtifactOne[position]);
            character.setArtifactTwo(characterArtifactTwo[position]);
            character.setCard(characterCard[position]);
            character.setVision(characterVision[position]);
            character.setArtifacta(characterArtifacta[position]);
            character.setArtifactb(characterArtifactb[position]);
            character.setArtifactc(characterArtifactc[position]);
            character.setArtifactd(characterArtifactd[position]);
            list.add(character);
        }
        return list;
    }
}