package com.dicoding.genshinapplication;

import java.util.ArrayList;

public class WeaponData {
    public static String[] weaponName = {
            "Amos' Bow",
            "Aquila Favonia",
            "Calamity Queller",
            "Elegy for the End",
            "Engulfing Lightning",
            "Everlasting Moonglow",
            "Freedom-Sworn",
            "Kagura's Verity",
            "Lost Prayer to the Sacred Winds",
            "Memory of Dust",
            "Mistsplitter Reforged",
            "Polar Star",
            "Primordial Jade Cutter",
            "Primordial Jade Winged-Spear",
            "Redhorn Stonethresher",
            "Skyward Atlas",
            "Skyward Blade",
            "Skyward Harp",
            "Skyward Pride",
            "Skyward Spine",
            "Song of Broken Pines",
            "Staff of Homa",
            "Summit Shaper",
            "The Unforged",
            "Thundering Pulse",
            "Vortex Vanquisher",
            "Wolf's Gravestone",
            "Akuoumaru",
            "Alley Hunter",
            "Amenoma Kageuchi",
            "Blackcliff Agate",
            "Blackcliff Longsword",
            "Blackcliff Pole",
            "Blackcliff Slasher",
            "Blackcliff Warbow",
            "Cinnabar Spindle",
            "Compound Bow",
            "Crescent Pike",
            "Deathmatch",
            "Dodoco Tales",
            "Dragon's Bane",
            "Dragonspine Spear",
            "Eye of Perception",
            "Favonius Codex",
            "Favonius Greatsword",
            "Favonius Lance",
            "Favonius Sword",
            "Favonius Warbow",
            "Festering Desire",
            "Frostbearer",
            "Hakushin Ring",
            "Hamayumi",
            "Iron Sting",
            "Katsuragikiri Nagamasa",
            "Kitain Cross Spear",
            "Lion's Roar",
            "Lithic Blade",
            "Lithic Spear",
            "Luxurious Sea-Lord",
            "Mappa Mare",
            "Mitternachts Waltz",
            "Mouun's Moon",
            "Oathsworn Eye",
            "Predator",
            "Prototype Amber",
            "Prototype Archaic",
            "Prototype Crescent",
            "Prototype Rancour",
            "Prototype Starglitter",
            "Rainslasher",
            "Royal Bow",
            "Royal Greatsword",
            "Royal Grimoire",
            "Royal Longsword",
            "Royal Spear",
            "Rust",
            "Sacrificial Bow",
            "Sacrificial Fragments",
            "Sacrificial Greatsword",
            "Sacrificial Sword",
            "Serpent Spine",
            "Snow-Tombed Starsilver",
            "Solar Pearl",
            "Sword of Descension",
            "The Alley Flash",
            "The Bell",
            "The Black Sword",
            "The Flute",
            "The Stringless",
            "The Viridescent Hunt",
            "The Widsith",
            "Wavebreaker's Fin",
            "Whiteblind",
            "Windblume Ode",
            "Wine and Song"
    };

    public  static String[] weaponBaseatk = {
            "608",
            "674",
            "741",
            "608",
            "608",
            "608",
            "608",
            "608",
            "608",
            "608",
            "674",
            "608",
            "542",
            "674",
            "542",
            "674",
            "608",
            "674",
            "674",
            "674",
            "741",
            "608",
            "608",
            "608",
            "608",
            "608",
            "608",
            "510",
            "565",
            "454",
            "510",
            "565",
            "510",
            "510",
            "565",
            "454",
            "454",
            "565",
            "454",
            "454",
            "454",
            "454",
            "454",
            "510",
            "454",
            "565",
            "454",
            "454",
            "510",
            "510",
            "565",
            "454",
            "510",
            "510",
            "565",
            "510",
            "510",
            "565",
            "454",
            "565",
            "510",
            "565",
            "565",
            "510",
            "510",
            "565",
            "510",
            "565",
            "510",
            "510",
            "510",
            "565",
            "565",
            "510",
            "565",
            "510",
            "565",
            "454",
            "565",
            "454",
            "510",
            "565",
            "510",
            "440",
            "620",
            "510",
            "510",
            "510",
            "510",
            "510",
            "510",
            "620",
            "510",
            "510",
            "565"
    };

    public static String[] weaponSecond = {
            "ATK 49.6%",
            "Physical DMG Bonus 41.3%",
            "ATK 16.5%",
            "Energy Recharge 55.1%",
            "Energy Recharge 55.1%",
            "HP 49.6%",
            "Elemental Mastery 198",
            "CRIT DMG 66.2%",
            "CRIT Rate 33.1%",
            "ATK 49.6%",
            "CRIT DMG 44.1%",
            "CRIT Rate 33.1%",
            "CRIT Rate 44.1%",
            "CRIT Rate 22.1%",
            "CRIT DMG 88.2%",
            "ATK 33.1%",
            "Energy Recharge 55.1%",
            "CRIT Rate 22.1%",
            "Energy Recharge 36.8%",
            "Energy Recharge 36.8%",
            "Physical DMG Bonus 20.7%",
            "CRIT DMG 66.2%",
            "ATK 49.6%",
            "ATK 49.6%",
            "CRIT DMG 66.2%",
            "ATK 49.6%",
            "ATK 49.6%",
            "ATK 41.3%",
            "ATK 27.6%",
            "ATK 55.1%",
            "CRIT DMG 55.1%",
            "CRIT DMG 36.8%",
            "CRIT DMG 55.1%",
            "CRIT DMG 55.1%",
            "CRIT DMG 36.8%",
            "DEF 69.0%",
            "Physical DMG Bonus 69.0%",
            "Physical DMG Bonus 34.5%",
            "CRIT Rate 36.8%",
            "ATK 55.1%",
            "Elemental Mastery 221",
            "Physical DMG Bonus 69.0%",
            "ATK 55.1%",
            "Energy Recharge 45.9%",
            "Energy Recharge 61.3%",
            "Energy Recharge 30.6%",
            "Energy Recharge 61.3%",
            "Energy Recharge 61.3%",
            "Energy Recharge 45.9%",
            "ATK 41.3%",
            "Energy Recharge 30.6%",
            "ATK 55.1%",
            "Elemental Mastery 165",
            "Energy Recharge 45.9%",
            "Elemental Mastery 110",
            "ATK 41.3%",
            "ATK 41.3%",
            "ATK 27.6%",
            "ATK 55.1%",
            "Elemental Mastery 110",
            "Physical DMG Bonus 51.7%",
            "ATK 27.6%",
            "ATK 27.6%",
            "ATK 41.3%",
            "HP 41.3%",
            "ATK 27.6%",
            "ATK 41.3%",
            "Physical DMG Bonus 34.5%",
            "Energy Recharge 45.9%",
            "Elemental Mastery 165",
            "ATK 41.3%",
            "ATK 27.6%",
            "ATK 27.6%",
            "ATK 41.3%",
            "ATK 27.6%",
            "ATK 41.3%",
            "Energy Recharge 30.6%",
            "Elemental Mastery 221",
            "Energy Recharge 30.6%",
            "Energy Recharge 61.3%",
            "CRIT Rate 27.6%",
            "Physical DMG Bonus 34.5%",
            "CRIT Rate 27.6%",
            "ATK 35.2%",
            "Elemental Mastery 55",
            "HP 41.3%",
            "CRIT Rate 27.6%",
            "ATK 41.3%",
            "Elemental Mastery 165",
            "CRIT Rate 27.6%",
            "CRIT DMG 55.1%",
            "ATK 13.8%",
            "DEF 51.7%",
            "Elemental Mastery 165",
            "Energy Recharge 30.6%"
    };

    public static String[] weaponPassive = {
            "Strong-Willed",
            "Falcon's Defiance",
            "Extinguishing Precept",
            "The Parting Refrain",
            "Timeless Dream: Eternal Stove",
            "Byakuya Kougetsu",
            "Revolutionary Chorale",
            "Kagura Dance of the Sacred Sakura",
            "Boundless Blessing",
            "Golden Majesty",
            "Mistsplitter's Edge",
            "Daylight's Augury",
            "Protector's Virtue",
            "Eagle Spear of Justice",
            "Gokadaiou Otogibanashi",
            "Wandering Clouds",
            "Sky-Piercing Fang",
            "Echoing Ballad",
            "Sky-ripping Dragon Spine",
            "Black Wing",
            "Rebel's Banner Hymn",
            "Reckless Cinnabar",
            "Golden Majesty",
            "Golden Majesty",
            "Rule By Thunder",
            "Golden Majesty",
            "Wolfish Tracker",
            "Watatsumi Wavewalker",
            "Oppidan Ambush",
            "Iwakura Succession",
            "Press the Advantage",
            "Press the Advantage",
            "Press the Advantage",
            "Press the Advantage",
            "Press the Advantage",
            "Spotless Heart",
            "Infusion Arrow",
            "Infusion Needle",
            "Gladiator",
            "Dodoventure!",
            "Bane of Flame and Water",
            "Frost Burial",
            "Echo",
            "Windfall",
            "Windfall",
            "Windfall",
            "Windfall",
            "Windfall",
            "Undying Admiration",
            "Frost Burial",
            "Sakura Saiguu",
            "Full Draw",
            "Infusion Stinger",
            "Samurai Conduct",
            "Samurai Conduct",
            "Bane of Fire and Thunder",
            "Lithic Axiom - Unity",
            "Lithic Axiom - Unity",
            "Oceanic Victory",
            "Infusion Scroll",
            "Evernight Duet",
            "Watatsumi Wavewalker",
            "People of the Faltering Light",
            "Strong Strike",
            "Gliding",
            "Crush",
            "Unreturning",
            "Smashed Stone",
            "Magic Affinity",
            "Bane of Storm and Tide",
            "Focus",
            "Focus",
            "Focus",
            "Focus",
            "Focus",
            "Rapid Firing",
            "Composed",
            "Composed",
            "Composed",
            "Composed",
            "Wavesplitter",
            "Frost Burial",
            "Solar Shine",
            "Descension",
            "Itinerant Hero",
            "Rebellious Guardian",
            "Justice",
            "Chord",
            "Arrowless Song",
            "Verdant Wind",
            "Debut",
            "Watatsumi Wavewalker",
            "Infusion Blade",
            "Windblume Wish",
            "Ever-Changing"
    };

    public static String[] weaponAbility = {
            "Increases Normal Attack and Charged Attack DMG by 12~24%. After a Normal or Charged Attack is fired, DMG dealt increases by a further 8~16% every 0.1 seconds the arrow is in the air for up to 5 times.",
            "ATK is increased by 20~40%. Triggers on taking DMG: the soul of the Falcon of the West awakens, holding the banner of the resistance aloft, regenerating HP equal to 100~160% of ATK and dealing 200~320% of ATK as DMG to surrounding opponents. This effect can only occur once every 15s.",
            "Gain 12~24% All Elemental DMG Bonus. Obtain Consummation for 20s after using an Elemental Skill, causing ATK to increase by 3.2~6.4% per second. This ATK increase has a maximum of 6 stacks. When the character equipped with this weapon is not on the field, Consummation's ATK increase is doubled.",
            "A part of the \"Millennial Movement\" that wanders amidst the winds.\n" +
                    "Increases Elemental Mastery by 60~120.\n" +
                    "When the Elemental Skills or Elemental Bursts of the character wielding this weapon hit opponents, that character gains a Sigil of Remembrance. This effect can be triggered once every 0.2s and can be triggered even if said character is not on the field.\n" +
                    "When you possess 4 Sigils of Remembrance, all of them will be consumed and all nearby party members will obtain the \"Millennial Movement: Farewell Song\" effect for 12s.\n" +
                    "\"Millennial Movement: Farewell Song\" increases Elemental Mastery by 100~200 and increases ATK by 20~40%. Once this effect is triggered, you will not gain Sigils of Remembrance for 20s.\n" +
                    "Of the many effects of the \"Millennial Movement,\" buffs of the same type will not stack.",
            "ATK increased by 28~56% of Energy Recharge over the base 100%. You can gain a maximum bonus of 80~120% ATK. Gain 30~50% Energy Recharge for 12s after using an Elemental Burst.",
            "Healing Bonus increased by 10~20%, Normal Attack DMG is increased by 1~3.0% of the Max HP of the character equipping this weapon. For 12s after using an Elemental Burst, Normal Attacks that hit opponents will restore 0.6 Energy. Energy can be restored this way once every 0.1s.",
            "A part of the \"Millennial Movement\" that wanders amidst the winds.\n" +
                    "Increases DMG by 10~20%.\n" +
                    "When the character wielding this weapon triggers Elemental Reactions, they gain a Sigil of Rebellion. This effect can be triggered once every 0.5s and can be triggered even if said character is not on the field.\n" +
                    "When you possess 2 Sigils of Rebellion, all of them will be consumed and all nearby party members will obtain \"Millennial Movement: Song of Resistance\" for 12s.\n" +
                    "\"Millennial Movement: Song of Resistance\" increases Normal, Charged, and Plunging Attack DMG by 16~32% and increases ATK by 20~40%. Once this effect is triggered, you will not gain Sigils of Rebellion for 20s.\n" +
                    "Of the many effects of the \"Millennial Movement,\" buffs of the same type will not stack.",
            "Gains the Kagura Dance effect when using an Elemental Skill, causing the Elemental Skill DMG of the character wielding this weapon to increase by 12~24% for 16s. Max 3 stacks. This character will gain 12~24% All Elemental DMG Bonus when they possess 3 stacks.",
            "Increases Movement SPD by 10%. When in battle, gain an 8~16% Elemental DMG Bonus every 4s. Max 4 stacks. Lasts until the character falls or leaves combat.",
            "Increases Shield Strength by 20~40%. Scoring hits on opponents increases ATK by 4~8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%",
            "Gain a 12~24% Elemental DMG Bonus for all elements and receive the might of the Mistsplitter's Emblem. At stack levels 1/2/3, Mistsplitter's Emblem provides a 8/16/28~16/32/56% Elemental DMG Bonus for the character's Elemental Type. The character will obtain 1 stack of Mistsplitter's Emblem in each of the following scenarios: Normal Attack deals Elemental DMG (stack lasts 5s), casting Elemental Burst (stack lasts 10s); Energy is less than 100% (stack disappears when Energy is full). Each stack's duration is calculated independently.",
            "Elemental Skill and Elemental Burst DMG increased by 12~24%. After a Normal Attack, Charged Attack, Elemental Skill or Elemental Burst hits an opponent, 1 stack of Ashen Nightstar will be gained for 12s. When 1/2/3/4 stacks of Ashen Nightstar are present, ATK is increased by 10/20/30/48~20/40/60/96%. The stack of Ashen Nightstar created by the Normal Attack, Charged Attack, Elemental Skill or Elemental Burst will be counted independently of the others.",
            "HP increased by 20~40%. Additionally, provides an ATK Bonus based on 1.2~2.4% of the wielder's Max HP.",
            "On hit, increases ATK by 3.2~6.0% for 6s. Max 7 stacks. This effect can only occur once every 0.3s. While in possession of the maximum possible stacks, DMG dealt is increased by 12~24%",
            "DEF is increased by 28~56%. Normal and Charged Attack DMG is increased by 40~80% of DEF.",
            "Increases Elemental DMG Bonus by 12~24%. Normal Attack hits have a 50% chance to earn the favor of the clouds. which actively seek out nearby opponents to attack for 15s, dealing 160~320% ATK DMG. Can only occur once every 30s.",
            "CRIT Rate increased by 4~8%. Gains Skypiercing Might upon using Elemental Burst: Increases Movement SPD by 10%, increases ATK SPD by 10%, and Normal and Charged hits deal additional DMG equal to 20~40% of ATK. Skypiercing Might lasts for 12s.",
            "Increases CRIT DMG by 20~40%. Hits have a 60~100% chance to inflict a small AoE attack, dealing 125% Physical ATK DMG. Can only occur once every 4~2s.",
            "Increases all DMG by 8~16%. After using an Elemental Burst, Normal or Charged Attack, on hit, creates a vacuum blade that does 80~160% of ATK as DMG to opponents along its path. Lasts for 20s or 8 vacuum blades.",
            "Increases CRIT Rate by 8~16% and increases Normal ATK SPD by 12%. Additionally, Normal and Charged Attacks hits on opponents have a 50% chance to trigger a vacuum blade that deals 40~100% of ATK as DMG in a small AoE. This effect can occur no more than once every 2s.",
            "A part of the \"Millennial Movement\" that wanders amidst the winds.\n" +
                    "Increases ATK by 16~32%, and when Normal or Charged Attacks hit opponents, the character gains a Sigil of Whispers. This effect can be triggered once every 0.3s.\n" +
                    "When you possess four Sigils of Whispers, all of them will be consumed and all nearby party members will obtain the \"Millennial Movement: Banner-Hymn\" effect for 12s.\n" +
                    "\"Millennial Movement: Banner-Hymn\" increases Normal ATK SPD by 12~24% and increases ATK by 20~40%. Once this effect is triggered, you will not gain Sigils of Whispers for 20s.\n" +
                    "Of the many effects of the \"Millennial Movement\", buffs of the same type will not stack.",
            "HP increased by 20~40%. Additionally, provides an ATK Bonus based on 0.8~1.6% of the wielder's Max HP. When the wielder's HP is less than 50%, this ATK bonus is increased by an additional 1~1.8% of Max HP.",
            "Increases Shield Strength by 20~40%. Scoring hits on opponents increases ATK by 4~8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%",
            "Increases Shield Strength by 20~40%. Scoring hits on opponents increases ATK by 4~8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%",
            "Increases ATK by 20~40% and grants the might of the Thunder Emblem. At stack levels 1/2/3, the Thunder Emblem increases Normal Attack DMG by 12/24/40~24/48/80%. The character will obtain 1 stack of Thunder Emblem in each of the following scenarios: Normal Attack deals DMG (stack lasts 5s), casting Elemental Skill (stack lasts 10s); Energy is less than 100% (stack disappears when Energy is full). Each stack's duration is calculated independently.",
            "Increases Shield Strength by 20~40%. Scoring hits on opponents increases ATK by 4~8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%",
            "Increases ATK by 20~40%. On hit, attacks against opponents with less than 30% HP increase all party members' ATK by 40~80% for 12s. Can only occur once every 30s.",
            "For every point of the entire party's combined maximum Energy capacity, the Elemental Burst DMG of the character equipping this weapon is increased by 0.12~0.24%. A maximum of 40~80% increased Elemental Burst DMG can be achieved this way.",
            "While the character equipped with this weapon is in the party but not on the field, their DMG increases by 2~4% every second up to a max of 20~40%. When the character is on the field for more than 4s, the aforementioned DMG buff decreases by 4~8% per second until it reaches 0%",
            "After casting an Elemental Skill, gain 1 Succession Seed. This effect can be triggered once every 5s. The Succession Seed lasts for 30s. Up to 3 Succession Seeds may exist simultaneously. After using an Elemental Burst, all Succession Seeds are consumed and after 2s, the character regenerates 6~12 Energy for each seed consumed.",
            "After defeating an opponent, ATK is increased by 12~24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
            "After defeating an opponent, ATK is increased by 12~24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
            "After defeating an opponent, ATK is increased by 12~24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
            "After defeating an opponent, ATK is increased by 12~24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
            "After defeating an opponent, ATK is increased by 12~24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
            "Elemental Skill DMG is increased by 40~80% of DEF. The effect will be triggered no more than once every 1.5s and will be cleared 0.1s after the Elemental Skill deals DMG.",
            "Normal Attack and Charged Attack hits increase ATK by 4~8% and Normal ATK SPD by 1.2~2.4% for 6s. Max 4 stacks. Can only occur once every 0.3s.",
            "After picking up an Elemental Orb/Particle, Normal and Charged Attacks deal an additional 20~40% ATK as DMG for 5s.",
            "If there are at least 2 opponents nearby, ATK is increased by 16~32% and DEF is increased by 16~32%. If there are fewer than 2 opponents nearby, ATK is increased by 24~48%",
            "Normal Attack hits on opponents increase Charged Attack DMG by 16~32% for 6s. Charged Attack hits on opponents increase ATK by 8~16% for 6s.",
            "Increases DMG against opponents affected by Hydro or Pyro by 20~36%",
            "Hitting an opponent with Normal and Charged Attacks has a 60~100% chance of forming and dropping an Everfrost Icicle above them, dealing 80~140% AoE ATK DMG. Opponents affected by Cryo are dealt 200~360% ATK DMG instead by the icicle. Can only occur once every 10s.",
            "Normal and Charged Attacks have a 50% chance to fire a Bolt of Perception, dealing 240~360% ATK as DMG. This bolt can bounce between opponents a maximum of 4 times. This effect can occur once every 12~8s.",
            "CRIT hits have a 60~100% chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every 12~6s.",
            "CRIT hits have a 60~100% chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every 12~6s.",
            "CRIT hits have a 60~100% chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every 12~6s.",
            "CRIT hits have a 60~100% chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every 12~6s.",
            "CRIT hits have a 60~100% chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every 12~6s.",
            "Increases Elemental Skill DMG by 16~32% and Elemental Skill CRIT Rate by 6~12%",
            "Hitting an opponent with Normal and Charged Attacks has a 60~100% chance of forming and dropping an Everfrost Icicle above them, dealing 80~140% AoE ATK DMG. Opponents affected by Cryo are dealt 200~360% ATK DMG instead by the icicle. Can only occur once every 10s.",
            "After the character equipped with this weapon triggers an Electro elemental reaction, nearby party members of an Elemental Type involved in the elemental reaction receive a 10~20% Elemental DMG Bonus for their element, lasting 6s. Elemental Bonuses gained in this way cannot be stacked.",
            "Increases Normal Attack DMG by 16~32% and Charged Attack DMG by 12~24%. When the equipping character's Energy reaches 100%, this effect is increased by 100%",
            "Dealing Elemental DMG increases all DMG by 6~12% for 6s. Max 2 stacks. Can only occur once every 1s.",
            "Increases Elemental Skill DMG by 6~12%. After Elemental Skill hits an opponent, the character loses 3 Energy but regenerates 3~5 Energy every 2s for the next 6s. This effect can occur once every 10s. Can be triggered even when the character is not on the field.",
            "Increases Elemental Skill DMG by 6~12%. After Elemental Skill hits an opponent, the character loses 3 Energy but regenerates 3~5 Energy every 2s for the next 6s. This effect can occur once every 10s. Can be triggered even when the character is not on the field.",
            "Increases DMG against enemies affected by Pyro or Electro by 20~36%",
            "For every character in the party who hails from Liyue, the character who equips this weapon gains 7~11% ATK increase and 3~7% CRIT Rate increase. This effect stacks up to 4 times.",
            "For every character in the party who hails from Liyue, the character who equips this weapon gains 7~11% ATK increase and 3~7% CRIT Rate increase. This effect stacks up to 4 times.",
            "Increases Elemental Burst DMG by 12~24%. When Elemental Burst hits opponents, there is a 100% chance of summoning a huge onrush of tuna that charges and deals 100~200% ATK as AoE DMG. This effect can occur once every 15s.",
            "Triggering an Elemental reaction grants a 8~16% Elemental DMG Bonus for 10s. Max 2 stacks.",
            "Normal Attack hits on opponents increase Elemental Skill DMG by 20~40% for 5s. Elemental Skill hits on opponents increase Normal Attack DMG by 20~40% for 5s.",
            "For every point of the entire party's combined maximum Energy capacity, the Elemental Burst DMG of the character equipping this weapon is increased by 0.12~0.24%. A maximum of 40~80% increased Elemental Burst DMG can be achieved this way.",
            "Increases Energy Recharge by 24~48% for 10s after using an Elemental Skill.",
            "Dealing Cryo DMG to opponents increases this character's Normal and Charged Attack DMG by 10% for 6s. This effect can have a maximum of 2 stacks.\n" +
                    "Additionally, when Aloy equips Predator, ATK is increased by 66.",
            "Using an Elemental Burst regenerates 4~6 Energy every 2s for 6s. All party members will regenerate 4~6% HP every 2s for this duration.",
            "On hit, Normal or Charged Attacks have a 50% chance to deal an additional 240~480% ATK DMG to opponents within a small AoE. Can only occur once every 15s.",
            "Charged Attack hits on weak points increase Movement SPD by 10% and ATK by 36~72% for 10s.",
            "On hit, Normal or Charged Attacks increase ATK and DEF by 4~8% for 6s. Max 4 stacks. Can only occur once every 0.3s.",
            "After using an Elemental Skill, increases Normal and Charged Attack DMG by 8~16% for 12s. Max 2 stacks.",
            "Increases DMG against opponents affected by Hydro or Electro by 20~36%",
            "Upon dealing damage to an opponent, increases CRIT Rate by 8~16%. Max 5 stacks. A CRIT hit removes all existing stacks.",
            "Upon dealing damage to an opponent, increases CRIT Rate by 8~16%. Max 5 stacks. A CRIT hit removes all existing stacks.",
            "Upon dealing damage to an opponent, increases CRIT Rate by 8~16%. Max 5 stacks. A CRIT hit removes all existing stacks.",
            "Upon dealing damage to an opponent, increases CRIT Rate by 8~16%. Max 5 stacks. A CRIT hit removes all existing stacks.",
            "Upon dealing damage to an opponent, increases CRIT Rate by 8~16%. Max 5 stacks. A CRIT hit removes all existing stacks.",
            "Increases Normal Attack DMG by 40~80% but decreases Charged Attack DMG by 10%",
            "After dealing damage to an opponent with an Elemental Skill, the skill has a 40~80% chance to end its own CD. Can only occur once every 30~16s.",
            "After dealing damage to an opponent with an Elemental Skill, the skill has a 40~80% chance to end its own CD. Can only occur once every 30~16s.",
            "After dealing damage to an opponent with an Elemental Skill, the skill has a 40~80% chance to end its own CD. Can only occur once every 30~16s.",
            "After dealing damage to an opponent with an Elemental Skill, the skill has a 40~80% chance to end its own CD. Can only occur once every 30~16s.",
            "Every 4s a character is on the field, they will deal 6~10% more DMG and take 3~2% more DMG. This effect has a maximum of 5 stacks and will not be reset if the character leaves the field, but will be reduced by 1 stack when the character takes DMG.",
            "Hitting an opponent with Normal and Charged Attacks has a 60~100% chance of forming and dropping an Everfrost Icicle above them, dealing 80~140% AoE ATK DMG. Opponents affected by Cryo are dealt 200~360% ATK DMG instead by the icicle. Can only occur once every 10s.",
            "Normal Attack hits increase Elemental Skill and Elemental Burst DMG by 20~40% for 6s. Likewise, Elemental Skill or Elemental Burst hits increase Normal Attack DMG by 20~40% for 6s.",
            "Hitting enemies with Normal or Charged Attacks grants a 50% chance to deal 200% ATK as DMG in a small AoE. This effect can only occur once every 10s.\n" +
                    "Additionally, if the Traveler equips the Sword of Descension, their ATK is increased by 66.",
            "Increases DMG dealt by the character equipping this weapon by 12~24%. Taking DMG disables this effect for 5s.",
            "Taking DMG generates a shield which absorbs DMG up to 20~32% of max HP. This shield lasts for 10s or until broken, and can only be triggered once every 45s. While protected by a shield, the character gains 12~24% increased DMG.",
            "Increases DMG dealt by Normal and Charged Attacks by 20~40%.\n" +
                    "Additionally, regenerates 60~100% of ATK as HP when Normal and Charged Attacks score a CRIT Hit. This effect can occur once every 5s.",
            "Normal or Charged Attacks grant a Harmonic on hits. Gaining 5 Harmonics triggers the power of music and deals 100~200% ATK DMG to surrounding enemies. Harmonics last up to 30s, and a maximum of 1 can be gained every 0.5s.",
            "Increases Elemental Skill and Elemental Burst DMG by 24~48%",
            "Upon hit, Normal and Aimed Shot Attacks have a 50% chance to generate a Cyclone, which will continuously attract surrounding opponents, dealing 40~80% of ATK as DMG to these opponents every 0.5s for 4s. This effect can only occur once every 14~10s.",
            "When a character takes the field, they will gain a random theme song for 10s. This can only occur once every 30s.\n" +
                    "Recitative: ATK is increased by 60~120%.\n" +
                    "Aria: Increases all Elemental DMG by 48~96%.\n" +
                    "Interlude: Elemental Mastery is increased by 240~480.",
            "For every point of the entire party's combined maximum Energy capacity, the Elemental Burst DMG of the character equipping this weapon is increased by 0.12~0.24%. A maximum of 40~80% increased Elemental Burst DMG can be achieved this way.",
            "On hit, Normal or Charged Attacks increase ATK and DEF by 6~12% for 6s. Max 4 stacks (24~48% total). Can only occur once every 0.5s.",
            "After using an Elemental Skill, receive a boon from the ancient wish of the Windblume, increasing ATK by 16~32% for 6s.",
            "Hitting an opponent with a Normal Attack decreases the Stamina consumption of Sprint or Alternate sprint by 14~22% for 5s. Additionally, using a Sprint or Alternate Sprint ability increases ATK by 20~40% for 5s."
    };

    public static int[] weaponCard = {
            R.drawable.amosbow,
            R.drawable.aquilafavonia,
            R.drawable.calamityqueller,
            R.drawable.elegyfortheend,
            R.drawable.engulfinglightning,
            R.drawable.everlastingmoonglow,
            R.drawable.freedomsworn,
            R.drawable.kagurasverity,
            R.drawable.lostprayertothesacredwinds,
            R.drawable.memoryofdust,
            R.drawable.mistsplitterreforged,
            R.drawable.polarstar,
            R.drawable.primordialjadecutter,
            R.drawable.primordialjadewingedspear,
            R.drawable.redhornstonethresher,
            R.drawable.skywardatlas,
            R.drawable.skywardblade,
            R.drawable.skywardharp,
            R.drawable.skywardpride,
            R.drawable.skywardspine,
            R.drawable.songofbrokenpines,
            R.drawable.staffofhoma,
            R.drawable.summitshaper,
            R.drawable.theunforged,
            R.drawable.thunderingpulse,
            R.drawable.vortexvanquisher,
            R.drawable.wolfsgravestone,
            R.drawable.akuoumaru,
            R.drawable.alleyhunter,
            R.drawable.amenomakageuchi,
            R.drawable.blackcliffagate,
            R.drawable.blackclifflongsword,
            R.drawable.blackcliffpole,
            R.drawable.blackcliffslasher,
            R.drawable.blackcliffwarbow,
            R.drawable.cinnabarspindle,
            R.drawable.compoundbow,
            R.drawable.crescentpike,
            R.drawable.deathmatch,
            R.drawable.dodocotales,
            R.drawable.dragonsbane,
            R.drawable.dragonspinespear,
            R.drawable.eyeofperception,
            R.drawable.favoniuscodex,
            R.drawable.favoniusgreatsword,
            R.drawable.favoniuslance,
            R.drawable.favoniussword,
            R.drawable.favoniuswarbow,
            R.drawable.festeringdesire,
            R.drawable.frostbearer,
            R.drawable.hakushinring,
            R.drawable.hamayumi,
            R.drawable.ironsting,
            R.drawable.katsuragikirinagamasa,
            R.drawable.kitaincrossspear,
            R.drawable.lionsroar,
            R.drawable.lithicblade,
            R.drawable.lithicspear,
            R.drawable.luxurioussealord,
            R.drawable.mappamare,
            R.drawable.mitternachtswaltz,
            R.drawable.mouunsmoon,
            R.drawable.oathsworneye,
            R.drawable.predator,
            R.drawable.prototypeamber,
            R.drawable.prototypearchaic,
            R.drawable.prototypecrescent,
            R.drawable.prototyperancour,
            R.drawable.prototypestarglitter,
            R.drawable.rainslasher,
            R.drawable.royalbow,
            R.drawable.royalgreatsword,
            R.drawable.royalgrimoire,
            R.drawable.royallongsword,
            R.drawable.royalspear,
            R.drawable.rust,
            R.drawable.sacrificialbow,
            R.drawable.sacrificialfragments,
            R.drawable.sacrificialgreatsword,
            R.drawable.sacrificialsword,
            R.drawable.serpentspine,
            R.drawable.snowtombedstarsilver,
            R.drawable.solarpearl,
            R.drawable.swordofdescension,
            R.drawable.thealleyflash,
            R.drawable.thebell,
            R.drawable.theblacksword,
            R.drawable.theflute,
            R.drawable.thestringless,
            R.drawable.theviridescenthunt,
            R.drawable.thewidsith,
            R.drawable.wavebreakersfin,
            R.drawable.whiteblind,
            R.drawable.windblumeode,
            R.drawable.wineandsong
    };

    public static int[] weaponBackground = {
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon5,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4,
            R.drawable.backgroundweapon4
    };

    static ArrayList<Weapon> getListData() {
        ArrayList<Weapon> list = new ArrayList<>();
        for(int position = 0; position < weaponName.length; position++) {
            Weapon weapon = new Weapon();
            weapon.setName(weaponName[position]);
            weapon.setCard(weaponCard[position]);
            weapon.setBaseatk(weaponBaseatk[position]);
            weapon.setSecond(weaponSecond[position]);
            weapon.setPassive(weaponPassive[position]);
            weapon.setAbility(weaponAbility[position]);
            weapon.setBackground(weaponBackground[position]);
            list.add(weapon);
        }
        return list;
    }
}